//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: inv.h
//
// MATLAB Coder version            : 4.0
// C/C++ source code generated on  : 03-May-2020 21:13:57
//

#ifndef INV2X2_H
#define INV2X2_H

// Include Files
#include <stddef.h>
#include <stdlib.h>
//#include "rtwtypes.h"
//#include "inv_types.h"

// Function Declarations
// Robust version is generated by MATLAB and is less accurate than the fast determinant based method, but it is more robust when approaching det=0
extern void inv2x2_robust(const float x[4], float y[4]);
extern void inv2x2_fast(const float x[4], float y[4]);

#endif

//
// File trailer for inv.h
//
// [EOF]
//
